
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: commits_app


test:
  <<: *default
  database: commits_app


production:
  <<: *default
  database: commits_app
  username: karen
  password: 
